---
all:
  children:
    dbservers:
      hosts:
        db-server:
          ansible_host: 192.168.1.222
          ansible_user: adminroot
    webservers:
      hosts:
        web-server:
          ansible_host: 192.168.1.221
          ansible_user: adminroot

  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

